### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by jrhwilson** [esolares/HapSolo#6]
Hi!

I'm trying to run HapSolo on our assembly, and I keep getting this error:

Traceback (most recent call last):
  File "hapsolo.py", line 835, in <module>
    WriteNewAssembly(myasmFileName, newasmfilename, mybestnscoreslist[i][1])
  File "hapsolo.py", line 790, in WriteNewAssembly
    myContigPositionsList = myContigsDict[contig]
KeyError: 'ptg001066'

I saw you mentioned about differences in generating each contig fasta but I've had a look at the contig and the busco directory and can't seem to see why this would be an issue. Do you know what might be going on?

Thanks

Jonathan

**Comment by esolares** [comment]
Hi Jonathon,

Just saw this. It looks like it's looking for contig ptg001066 but it doesn't seem to exist in the dictionary. I will look into it.

Again, sorry for the late reply. 

Thank you,

Edwin

**Comment by esolares** [comment]
Hi,

Sorry for the late reply. Could you please update your version of hapsolo and run it again? It should now write a log file that will help me understand what is causing the crash.

Thank you again for your time. I greatly appreciate it.

Thank you,

Edwin Solares
