### ISSUE TITLE
Error related with busco

### ISSUE THREAD

**Issue by anacatarinaas** [esolares/HapSolo#7]
Hi,

Does hapsolo only work with busco3? I am having this error when I run hapsolo and maybe is related to the version, in the cluster I have access to they don't have that version and I can't install it myself. What is hapsolo using from busco? Maybe I can try to get the file ready myself?

Thanks for any help you can provide
Cheers,
Ana

hapsolo.py -t 32 -i Mtar.fasta --paf Mtar_self_align.paf -b busco/

Traceback (most recent call last):
  File "/shared/home/asilva/HapSolo/hapsolo.py", line 819, in <module>
    busco2contigdict, contigs2buscodict = importBuscos(buscofileloc)
  File "/shared/home/asilva/HapSolo/hapsolo.py", line 196, in importBuscos
    for line in open(mybuscofiles[0]):
IndexError: list index out of range

**Comment by OZTaekOppa** [comment]
Hi,

I am having a similar issue despite the BUSCO3 outcome. 

/work/HapSolo/hapsolo.py -i SPO_CN1KCt_RN.fasta --paf /work/HapSolo/MM2/HS1_SPO_Self.paf -b /work/HapSolo/BUSCOTestDef_v4/run_BC_SPOCN1KCT_AllV32 -t 10

I have also tried to indicate as /work/HapSolo/BUSCOTestDef_v4/ but no luck. 

Traceback (most recent call last):
  File "/work/HapSolo/hapsolo.py", line 819, in <module>
    busco2contigdict, contigs2buscodict = importBuscos(buscofileloc)
  File "/work/HapSolo/hapsolo.py", line 196, in importBuscos
    for line in open(mybuscofiles[0]):
IndexError: list index out of range

Any suggestion? 

Cheers

**Comment by sunnycqcn** [comment]
> Hi,
> 
> I am having a similar issue despite the BUSCO3 outcome.
> 
> /work/HapSolo/hapsolo.py -i SPO_CN1KCt_RN.fasta --paf /work/HapSolo/MM2/HS1_SPO_Self.paf -b /work/HapSolo/BUSCOTestDef_v4/run_BC_SPOCN1KCT_AllV32 -t 10
> 
> I have also tried to indicate as /work/HapSolo/BUSCOTestDef_v4/ but no luck.
> 
> Traceback (most recent call last):
> File "/work/HapSolo/hapsolo.py", line 819, in
> busco2contigdict, contigs2buscodict = importBuscos(buscofileloc)
> File "/work/HapSolo/hapsolo.py", line 196, in importBuscos
> for line in open(mybuscofiles[0]):
> IndexError: list index out of range
> 
> Any suggestion?
> 
> Cheers

I met the same issue.
Did you know how to solve it?
Thanks,
Fuyou

**Comment by esolares** [comment]
Hi unfortunately it does not. I do however have a singularity image with the supported BUSCO version. My apologies for not getting to this earlier. I have been busy with moving and starting my new post doc position. I will work on fixing the bugs as well as adding support for different versions of BUSCO.

**Comment by parkgyuhwang** [comment]
Change the busco result file name like this : `full_table_***.tsv`

Chage the busco result file form like this :
```
# BUSCO version is: 3.0.0
# The lineage dataset is: sample dataset BUSCO 2.0 (Creation date:
07.10.2016, number of species: 23, number of BUSCOs: 10)
# To reproduce this run: python scripts/run_BUSCO.py -i sample_data/target.fa -o TEST -l sample_data/example -m genome -c 1 -f
#
BUSCO_1 Complete sample 30184 31421 320.9 193
BUSCO_2 Complete sample 31646 47625 872.0 443
BUSCO_3 Complete sample 62761 68675 241.8 146
```

**Comment by yschoeneberg** [comment]
For me, the issue was resolved by simply changing line 192 in script hapsolo.py from 
`mybuscofiles = glob.glob(buscofileloc + '/busco*/*/full_table_*.tsv')`
to
`mybuscofiles = glob.glob(buscofileloc + '/full_table_*.tsv')`

**Comment by esolares** [comment]
Yes you can either create the tsv files or update the line of code so it points to your file. If you do not have a directory of busco1 to buscon directories in your -b argument, it will not find your tsv files.
